# This file was generated by GoReleaser. DO NOT EDIT.
cask "tailor" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "0d3e88eeba9707e6742e8f32863f088f7bb9996834f5ecb6d5432dd6fb90cae7"
      url "https://github.com/wimpysworld/tailor/releases/download/v#{version}/tailor_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "06a41588c7bd7069b0fc27ed7c1d248f9e2bcacaa8aed80170b490a5000c4cd6"
      url "https://github.com/wimpysworld/tailor/releases/download/v#{version}/tailor_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8fbfd109afefd3318815e2224445640ee7a5eb514d22799a9ead68eafd0fe53c"
      url "https://github.com/wimpysworld/tailor/releases/download/v#{version}/tailor_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f1fba47e1c02d01dace5eeb2ccea6b91a4b5d9858b617bebef2f68a5687b1041"
      url "https://github.com/wimpysworld/tailor/releases/download/v#{version}/tailor_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tailor"
  desc "Ready-to-wear project templates for GitHub repositories."
  homepage "https://github.com/wimpysworld/tailor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tailor"

  # No zap stanza required
end
