# This file was generated by GoReleaser. DO NOT EDIT.
cask "tailor" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "fccbc3078f78be20fd65021cabface880c3f70f3bc6a1498cfd5f1c6728a0fef"
      url "https://github.com/wimpysworld/tailor/releases/download/v#{version}/tailor_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ba5d091df3cd1431ee053eb5bf1e7d67ac52d87bc8f4960262439f9a5feb312b"
      url "https://github.com/wimpysworld/tailor/releases/download/v#{version}/tailor_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9cb80e2eef56923adb61d207440df2ffccb2ef7ecbd6bb8cb0944ccd1f8835ba"
      url "https://github.com/wimpysworld/tailor/releases/download/v#{version}/tailor_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "28653e86e8b7cea49262c1da892e3b1d94ff88661b475e0c46fe0d6e259dc937"
      url "https://github.com/wimpysworld/tailor/releases/download/v#{version}/tailor_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tailor"
  desc "Ready-to-wear project templates for GitHub repositories."
  homepage "https://github.com/wimpysworld/tailor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tailor"

  # No zap stanza required
end
